title       = "pypi"
baseURL     = "https://pypi-cli.tamnd.com/"
description = "Browse the PyPI Python package index"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/pypi-cli"
